comment/comment/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'comment.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('my_app.urls', namespace='my_app')),
    url(r'^admin/', include(admin.site.urls)),
]

comment/my_app/urls.py
from django.conf.urls import patterns, url
from my_app import views

urlpatterns = patterns(
    '',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^create_comment/$', views.CommentCreateView.as_view(),
        name='create_comment'),
)

comment/my_app/models.py
from django.db import models


class Comment(models.Model):
    body = models.TextField()
    created_data = models.DateTimeField(auto_now_add=True)
    last_updated_data = models.DateTimeField(auto_now=True)
    is_inappropriate = models.BooleanField(default=False)
    RANKING_CHOICES = (
        (0, "0"),
        (1, "1"),
        (2, "2"),
        (3, "3"),
        (4, "4"),
        (5, "5")
    )
    ranking = models.IntegerField(choices=RANKING_CHOICES, default=1)

    def __str__(self):
        return self.body

comment/my_app/forms.py
from django import forms

from my_app.models import Comment


class CommentsCreateForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = [
            'body'
        ]

    def save(self, commit=True):
        comment = super(CommentsCreateForm, self).save(commit=False)
        if commit:
            comment.save()
        return comment

comment/my_app/views.py
from django.views import generic
from my_app import forms
from my_app import models


class IndexView(generic.ListView):
    template_name = 'my_app/index.html'
    model = models.Comment
    context_object_name = "comments"


class CommentCreateView(generic.CreateView):
    template_name = 'my_app/create_comment.html'
    form_class = forms.CommentsCreateForm
    success_url = '/'

comment/common/templates/common/base.html
{% load staticfiles %}

<!doctype html>
<html class="no-js">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}Coder Room Mate{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'common/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'common/css/bootstrap-theme.min.css' %}">
        {% block extra-head-tags %}{% endblock %}
    </head>
    <body>

        <!--[if lt IE 8]>
            <div class="container">
                <div class="alert alert-info" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
                    Estás usando un <strong>navegador antiguo</strong>. Por favor, <a href="http://browsehappy.com/">actualizalo</a> para mejorar tu experiencia.
                </div>
            </div>
        <![endif]-->

        {% block content %}{% endblock %}
        <script src="{% static 'common/js/vendor/jquery.min.js' %}"></script>
        <script src="{% static 'common/js/vendor/bootstrap.min.js' %}"></script>
        {% block extra-script-tags %}{% endblock %}
    </body>
</html>

comment/my_app/templates/my_app/create_comment.html
{% extends 'common/base.html' %}

{% load bootstrap3 %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h1>Register</h1>
            <form enctype="multipart/form-data" action="#" method="post" class="form" novalidate>
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                <button type="submit" class="btn btn-success">Register</button>
                {% endbuttons %}
            </form>
        </div><!-- col-md -->
    </div><!-- row -->
</div>

{% endblock %}

comment/my_app/templates/my_app/index.html
{% extends 'common/base.html' %}

{% load bootstrap3 %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h1>Comment Index</h1>
			<table class="table table-striped">
				{% for comment in comments%}
				<tr>

						<td>
						testing : {{ comment.body }}
						</td>
						<td>
							<a href="#"><i class="icon-pencil"></i> Edit</a>
						</td>
						<td>
							<a href="#"><i class="icon-trash"></i> Delete</a>
						</td>

				</tr>
				<a class="btn" href="#"><i class="icon-align-left"></i></a>
				{% empty %}
				<div>
					<h3>No comments in database, add a new one!</h3>
				</div>
				{% endfor %}
			</table>
			{% buttons %}
			<a type="submit" class="btn btn-primary" href="{% url 'my_app:create_comment' %}" >Create Comment</a>
			{% endbuttons %}
		</div><!-- col-md -->
	</div><!-- row -->
</div>

{% endblock %}